//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelFileNumberToName.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExcelFileNumberToName.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   ExcelFileNumberToName に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   セル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Cell {
            get {
                return ResourceManager.GetString("Cell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   調査ファイルクリア に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ClearExaminationFile {
            get {
                return ResourceManager.GetString("ClearExaminationFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   調査ファイル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExaminationFile {
            get {
                return ResourceManager.GetString("ExaminationFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   調査ファイルキーワード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExaminationFileKeyword {
            get {
                return ResourceManager.GetString("ExaminationFileKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   調査結果 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExaminationResult {
            get {
                return ResourceManager.GetString("ExaminationResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   調査設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExaminationSetting {
            get {
                return ResourceManager.GetString("ExaminationSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   調査対象 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExaminationTarget {
            get {
                return ResourceManager.GetString("ExaminationTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   調査実施 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExecuteExamination {
            get {
                return ResourceManager.GetString("ExecuteExamination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   重要なお知らせ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ImportantNotice {
            get {
                return ResourceManager.GetString("ImportantNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メモ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Memo {
            get {
                return ResourceManager.GetString("Memo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   致命的なエラーが発生しました｡
        ///このアプリケーションを終了します｡
        ///エラーの詳細な情報を表示しますか? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageFatalError {
            get {
                return ResourceManager.GetString("MessageFatalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   調査したいファイル　もしくは　調査したいファイルが含まれるフォルダを
        ///ドラッグ&amp;ドロップしてください｡
        ///調査ファイルキーワードを含むファイルのみ調査ファイルに登録されます｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageGuideDragAndDrop {
            get {
                return ResourceManager.GetString("MessageGuideDragAndDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このアプリケーションのプロジェクトURLを開く に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageOpenProjectUrl {
            get {
                return ResourceManager.GetString("MessageOpenProjectUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   準備が完了しました｡｢調査実施｣ボタン押下で検査を行います｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageStatusAlreadyExamination {
            get {
                return ResourceManager.GetString("MessageStatusAlreadyExamination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   調査ファイルが指定されていません｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageStatusExaminationFileEmpty {
            get {
                return ResourceManager.GetString("MessageStatusExaminationFileEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   調査対象が設定されていません｡ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageStatusExaminationTargetEmpty {
            get {
                return ResourceManager.GetString("MessageStatusExaminationTargetEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   名称 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   数値 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プリセット に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Preset {
            get {
                return ResourceManager.GetString("Preset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   シート に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Sheet {
            get {
                return ResourceManager.GetString("Sheet", resourceCulture);
            }
        }
    }
}
